# Generated by Django 4.2.7 on 2023-12-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('Grass', 'Grass'), ('Hard', 'Hard'), ('Mud', 'Mud'), ('Redsand', 'Redsand')], max_length=20, null=True),
        ),
    ]
